paths:
  /api/products:
    get:
      summary: Devuelve varios productos o todos dependiendo de los parámetros. Si el tipo de usuario es del tipo administrador, devuelve todos los productos (considerando la seleccion que se pueda hacer con los parametros , o bien solo devuelve los productos correspondientes al usuario que hizo Login
      tags:
        - products
      parameters:
        - name: category
          in: query
          description: Categoría de los productos que se desean obtener, si se omite devuelve todos
          required: false
          schema:
            type: string
        - name: stock
          in: query
          description: Stock de los productos que se desean consultar, si se omite devuelve todos
          required: false
          schema:
            type: integer
        - name: sort
          in: query
          description: Clasifica los productos por orden descendente de precio si se especifica 'desc', caso contrario lo hace en forma ascendente
          required: false
          schema:
            type: string
        - name: page
          in: query
          description: Número de página desde la cual se desean obtener los productos, si se omite considera 1
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Cantidad de productos a obtener por página, si se omite considera 10 productos por pagina
          required: false
          schema:
            type: integer
      responses:
        '500': 
          description: Error inesperado al tratar de recuperar los productos solicitados
    post:
      summary: Crea un producto nuevo
      tags:
        - products
      consumes: 
        - application/json
      parameters:
        - in: body
          name: product
          description: Datos del producto a crear
          schema:
            type: object
            required: true
            properties:
              code:
                type: string
                required: true
              title:
                type: string
                required: true
              description:
                type: string
                required: true
              price:
                type: integer
                required: true
              stock:
                type: integer
                required: true
              thumbnail:
                type: array
                items: 
                  type: string
                required: false
              status:
                type: boolean
                required: false
      responses:
        '200':
          description: Producto creado correctamente
        '400':
          description: Código de producto ya existe
        '500': 
          description: Error inesperado al tratar de crear un producto
    
  /api/products/{pid}:
    get:
      summary: Devuelve la información de un producto por su ID
      tags:
        - products
      parameters:
        - name: pid
          in: path
          description: Identificación del producto solicitado
          required: true
          schema:
            type: string
      responses:
        '404':
          description: El producto requerido no existe
        '452':
          description: El identificador del producto no es válido (debe ser un string con formato válido de un object ID de MongoDB)
        '500': 
          description: Error inesperado al tratar obtener un producto por su ID
    put:
      summary: Actualiza un producto por su ID
      tags:
        - products
      consumes: 
        - application/json
      parameters:
        - name: pid
          in: path
          description: Identificación del producto a modificar
          required: true
          schema:
            type: string
        - in: body
          name: product
          description: Datos del producto a modificar
          schema:
            type: object
            required: true
            properties:
              title:
                type: string
                required: false
              description:
                type: string
                required: false
              price:
                type: integer
                required: false
              stock:
                type: integer
                required: false
              thumbnail:
                type: array
                items: 
                  type: string
                required: false
              status:
                type: boolean
                required: false
      responses:
        '403': 
          description: Usuario no autorizado a hacer esta transacción
        '404':
          description: El producto requerido no existe
        '452':
          description: El identificador del producto no es válido (debe ser un string con formato válido de un object ID de MongoDB)
        '453': 
          description: Datos faltantes o inválidos
    delete:
      summary: Borra un producto por su ID
      tags:
        - products
      parameters:
        - name: pid
          in: path
          description: Identificación del producto a eliminar
          required: true
          schema:
            type: string
      responses:
        '201':
          description:  Producto eliminado correctamente
        '403': 
          description: Usuario no autorizado a hacer esta transacción
        '404':
          description: El producto requerido no existe
        '452':
          description: El identificador del producto no es válido (debe ser un string con formato válido de un object Id de MongoDB)
        '500': 
          description: Error inesperado al tratar de eliminar un producto
  /api/mockingproducts:
    get:
      summary: Devuelve la información de 100 productos inventados por faker-js
      tags:
        - mockingproducts
      responses:
        '200':
          description:  Devuelve la lista de los 100 productos inventados en formato json
